# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-06-29 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartshark', '0038_jobverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginexecution',
            name='execution_type',
            field=models.CharField(blank=True, choices=[('all', 'Executed on all revisions'), ('new', 'Executed on new revisions'), ('rev', 'Executed on specified revisions'), ('error', 'Executed on revisions that previously threw an error'), ('ver', 'Execute on all revisions where verification failed for one Plugin')], max_length=5, null=True),
        ),
    ]
